//
//  DeveloperPreview.swift
//  TREE
//
//  Created by Jaewon Oh on 7/14/25.
//

import Foundation

class DeveloperPreview {
    
    static let shared = DeveloperPreview()
    
    // MARK: - mock sublets
    var sublets: [Sublets] = [
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Jason",
            ownerImageUrl: "profile",
            numberOfBedrooms: 1,
            numberOfBathrooms: 1,
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image", "Image1", "Image2"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            shared: true,
            leaseTermMonth: "[07/02-10/12]",
            leaseTermYear: "2025",
            rentFee: 1500,
            title: "Cozy 2BR/1BA Apartment in Berkeley",
            explanation: "Welcome to our bright and spacious 2-bedroom, 1-bathroom apartment located just 10 minutes from UC Berkeley campus!, rent fee and lease terms are negotiable"
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Jason",
            ownerImageUrl: "profile",
            numberOfBedrooms: 1,
            numberOfBathrooms: 1,
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image2", "Image", "Image1"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            shared: true,
            leaseTermMonth: "[07/02-10/12]",
            leaseTermYear: "2025",
            rentFee: 1500,
            title: "Cozy 2BR/1BA Apartment in Berkeley",
            explanation: "Welcome to our bright and spacious 2-bedroom, 1-bathroom apartment located just 10 minutes from UC Berkeley campus!, rent fee and lease terms are negotiable"
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Jason",
            ownerImageUrl: "profile",
            numberOfBedrooms: 1,
            numberOfBathrooms: 1,
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image1", "Image", "Image2"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            shared: true,
            leaseTermMonth: "[07/02-10/12]",
            leaseTermYear: "2025",
            rentFee: 1500,
            title: "Cozy 2BR/1BA Apartment in Berkeley",
            explanation: "Welcome to our bright and spacious 2-bedroom, 1-bathroom apartment located just 10 minutes from UC Berkeley campus!, rent fee and lease terms are negotiable"
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Jason",
            ownerImageUrl: "profile",
            numberOfBedrooms: 1,
            numberOfBathrooms: 1,
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image", "Image2", "Image1"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            shared: true,
            leaseTermMonth: "[07/02-10/12]",
            leaseTermYear: "2025",
            rentFee: 1500,
            title: "Cozy 2BR/1BA Apartment in Berkeley",
            explanation: "Welcome to our bright and spacious 2-bedroom, 1-bathroom apartment located just 10 minutes from UC Berkeley campus!, rent fee and lease terms are negotiable"
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Jason",
            ownerImageUrl: "profile",
            numberOfBedrooms: 1,
            numberOfBathrooms: 1,
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image2", "Image", "Image1"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            shared: true,
            leaseTermMonth: "[07/02-10/12]",
            leaseTermYear: "2025",
            rentFee: 1500,
            title: "Cozy 2BR/1BA Apartment in Berkeley",
            explanation: "Welcome to our bright and spacious 2-bedroom, 1-bathroom apartment located just 10 minutes from UC Berkeley campus!, rent fee and lease terms are negotiable"
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Jason",
            ownerImageUrl: "profile",
            numberOfBedrooms: 1,
            numberOfBathrooms: 1,
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image", "Image1", "Image2"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            shared: true,
            leaseTermMonth: "[07/02-10/12]",
            leaseTermYear: "2025",
            rentFee: 1500,
            title: "Cozy 2BR/1BA Apartment in Berkeley",
            explanation: "Welcome to our bright and spacious 2-bedroom, 1-bathroom apartment located just 10 minutes from UC Berkeley campus!, rent fee and lease terms are negotiable"
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Jason",
            ownerImageUrl: "profile",
            numberOfBedrooms: 1,
            numberOfBathrooms: 1,
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image", "Image1", "Image2"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            shared: true,
            leaseTermMonth: "[07/02-10/12]",
            leaseTermYear: "2025",
            rentFee: 1500,
            title: "Cozy 2BR/1BA Apartment in Berkeley",
            explanation: "Welcome to our bright and spacious 2-bedroom, 1-bathroom apartment located just 10 minutes from UC Berkeley campus!, rent fee and lease terms are negotiable"
        )
    ]
    // MARK: - mock store products
    var stores: [Stores] = [
        .init(
            id: NSUUID().uuidString,
            productName: "Television",
            ownerUid: NSUUID().uuidString,
            ownerName: "Bob",
            ownerImageUrl: "profile",
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image3", "Image3", "Image3"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            price: 80,
            title: "stunning 65-inch 4K Smart TV 📺 featuring vibrant colors 🌈 and crystal-clear picture quality! 💎🔥🏠",
            explanation: "Bought this for $130, 5 months ago. Selling this $50 cheaper than original price!"
        ),
        .init(
            id: NSUUID().uuidString,
            productName: "Microwave",
            ownerUid: NSUUID().uuidString,
            ownerName: "Dobby",
            ownerImageUrl: "profile",
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image4", "Image4", "Image1"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            price: 20,
            title: "Cheap Microwave",
            explanation: "Bought this for $100, 3 months ago. Selling this $80 cheaper than original price!"
        ),
        .init(
            id: NSUUID().uuidString,
            productName: "Television",
            ownerUid: NSUUID().uuidString,
            ownerName: "Bob",
            ownerImageUrl: "profile",
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image3", "Image3", "Image3"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            price: 80,
            title: "Cheap TV",
            explanation: "stunning 65-inch 4K Smart TV 📺 featuring vibrant colors 🌈 and crystal-clear picture quality! 💎🔥🏠"
        ),
        .init(
            id: NSUUID().uuidString,
            productName: "Microwave",
            ownerUid: NSUUID().uuidString,
            ownerName: "Dobby",
            ownerImageUrl: "profile",
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image4", "Image4", "Image1"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            price: 20,
            title: "Cheap Microwave",
            explanation: "Bought this for $100, 3 months ago. Selling this $80 cheaper than original price!"
        ),
        .init(
            id: NSUUID().uuidString,
            productName: "Television",
            ownerUid: NSUUID().uuidString,
            ownerName: "Bob",
            ownerImageUrl: "profile",
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image3", "Image3", "Image3"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            price: 80,
            title: "Cheap TV",
            explanation: "stunning 65-inch 4K Smart TV 📺 featuring vibrant colors 🌈 and crystal-clear picture quality! 💎🔥🏠"
        ),
        .init(
            id: NSUUID().uuidString,
            productName: "Microwave",
            ownerUid: NSUUID().uuidString,
            ownerName: "Dobby",
            ownerImageUrl: "profile",
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image4", "Image4", "Image1"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            price: 20,
            title: "Cheap Microwave",
            explanation: "Bought this for $100, 3 months ago. Selling this $80 cheaper than original price!"
        ),
        .init(
            id: NSUUID().uuidString,
            productName: "Television",
            ownerUid: NSUUID().uuidString,
            ownerName: "Bob",
            ownerImageUrl: "profile",
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image3", "Image3", "Image3"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            price: 80,
            title: "Cheap TV",
            explanation: "Bought this for $130, 5 months ago. Selling this $50 cheaper than original price!"
        ),
        .init(
            id: NSUUID().uuidString,
            productName: "Microwave",
            ownerUid: NSUUID().uuidString,
            ownerName: "Dobby",
            ownerImageUrl: "profile",
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image4", "Image4", "Image1"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            price: 20,
            title: "Cheap Microwave",
            explanation: "Bought this for $100, 3 months ago. Selling this $80 cheaper than original price!"
        ),
        .init(
            id: NSUUID().uuidString,
            productName: "Television",
            ownerUid: NSUUID().uuidString,
            ownerName: "Bob",
            ownerImageUrl: "profile",
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image3", "Image3", "Image3"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            price: 80,
            title: "Cheap TV",
            explanation: "Bought this for $130, 5 months ago. Selling this $50 cheaper than original price!"
        ),
        .init(
            id: NSUUID().uuidString,
            productName: "Microwave",
            ownerUid: NSUUID().uuidString,
            ownerName: "Dobby",
            ownerImageUrl: "profile",
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image4", "Image4", "Image1"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            price: 20,
            title: "Cheap Microwave",
            explanation: "Bought this for $100, 3 months ago. Selling this $80 cheaper than original price!"
        ),
        .init(
            id: NSUUID().uuidString,
            productName: "Television",
            ownerUid: NSUUID().uuidString,
            ownerName: "Bob",
            ownerImageUrl: "profile",
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image3", "Image3", "Image3"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            price: 80,
            title: "Cheap TV",
            explanation: "Bought this for $130, 5 months ago. Selling this $50 cheaper than original price!"
        ),
        .init(
            id: NSUUID().uuidString,
            productName: "Microwave",
            ownerUid: NSUUID().uuidString,
            ownerName: "Dobby",
            ownerImageUrl: "profile",
            latitude: 37.871666,
            longitude: -122.272781,
            zipcode: "94704",
            imageURLs: ["Image4", "Image4", "Image1"],
            address: "2520 Hillegass Ave",
            city: "Berkeley",
            state: "California",
            price: 20,
            title: "Cheap Microwave",
            explanation: "Bought this for $100, 3 months ago. Selling this $80 cheaper than original price!"
        ),
    ]
}
